### ISSUE TITLE
Update an Existing MSIX File

### ISSUE THREAD

**Issue by Imran-imtiaz48** [microsoft/mggraph-intune-samples#13] opened 2024-08-08 05:27 UTC

**Comment by Mahopper** [comment] 2024-10-08 14:35
Hi @Imran-imtiaz48, just to confirm- this request for an MSIX uploaded directly as a LOB app to Intune, not wrapped as an .intunewin?

**Comment by Mahopper** [comment] 2024-11-02 21:39
Duplicate of https://github.com/microsoft/mggraph-intune-samples/issues/2

**Closed** 2024-11-02 21:39 UTC
Labels: duplicate, sample script request
